### ISSUE TITLE
there's an issue here 

### ISSUE THREAD

**Issue by abahe** [ezatpanah/DataStore-Youtube#1]
Process: com.ezatpanah.datastore_youtube, PID: 8023
    java.lang.IllegalStateException: There are multiple DataStores active for the same file: /data/user/0/com.ezatpanah.datastore_youtube/files/datastore/THEME_KEY.preferences_pb. You should either maintain your DataStore as a singleton or confirm that there is no two DataStore's active on the same file (by confirming that the scope is cancelled).

**Comment by ezatpanah** [comment]
Thanks for your feedback 👍
